language: r
r:
  - oldrel
  - release
  - devel

apt_packages:
  - libxml2-dev

install:
  - R -e "0" --args --bootstrap-packrat

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

script:
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::test()'
