language: r
r:
  - oldrel
  - release
  - devel

before_install:
  - sudo apt-get -y install libxml2-dev
  - sudo curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
  - sudo apt-get update
  - sudo ACCEPT_EULA=Y apt-get install msodbcsql17
  - sudo apt-get install unixodbc-dev

install:
  - R -e "0" --args --bootstrap-packrat

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

script:
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::test()'
